const Data = {
  "Research Services": [
    {
      id: 1,
      title: "Biocompatibility Tests",
      info: "ISO 10993-5:2009 Biological evaluation of medical devices Part 5: Tests for in vitro cytotoxicity ISO 10993-4:2002/Amd 1:2006 Biological evaluation of medical devices Part 4: Selection of tests for interactions with blood ISO 10993-12:2007 Biological evaluation of medical devices Part 12: Sample preparation and reference materials.",
      author: "Maria Butnaru",
      authorImg: "../../assets/blank.png",
    },
    {
      id: 2,
      title: "Biodegradation Tests",
      info: "ISO 10993-13 (adapted): Identification and quantification of degradation products of polymer-based medical devices ISO 10993-14 (adapted): Identification and quantification of degradation products of ceramic-based medical devices.",
      author: "Liliana VERESTIUC",
      authorImg: "../../assets/Verestiuc.png",
    },
    {
      id: 3,
      title: "Cell culture",
      info: "Primary and line cells: fibroblasts, osteoblasts, endothelial cells, stem cells, co-cultures.",
      author: ["Vera BALAN", "Vlad URSACHI"],
      authorImg: "../../assets/blank.png",
    },
    {
      id: 4,
      title: "Magnetic micro/nanoparticles",
      info: "Magnetic micro and nanoparticles/nanocapsules for diagnosis and therapy: magnetic nanoparticles coalted with polymers and functionalized with biomolecules.",
      author: ["Maria BUTNARU", "Andreea LUCA"],
      authorImg: "../../assets/blank.png",
    },
    {
      id: 5,
      title:
        "Polymeric scaffolds with applications in tissue engineering and regenerative medicine",
      info: "Bioactive scaffolds for skin tissue engineering. Preparation of scaffolds with active ingredients (anti-inflammatory drugs, antimicrobian agents, growth factors).Scaffolds for bone tissue engineering(biologically active scaffolds based on polymers - calcium phosphates) obtained by biomimetic methods. Unconventional techniques for materials biocompatibilization: imobilization of linear homo and heterobifunctional polymeric derivatives (PEG derivatives and dendrimers as artificial biomimetic proteins) as a spacer for cell adhesion molecules; immobilization of cell adhesive molecules (RGD peptides and extracellular matrix-derived adhesive peptides)..",
      author: "Florina Daniela IVAN",
      authorImg: "../../assets/blank.png",
    },
    {
      id: 6,
      title: "In vitro drug delivery studies",
      info: "Kinetics of drug delivery in simulated body fluids. Ex vivo models for drug delivery studies (cornea, transdermal studies)..",
      author: "",
      authorImg: "../../assets/blank.png",
    },
    {
      id: 7,
      title: "Biomaterials bioadhesive properties",
      info: "Bioadhesion is an important property that allows cells and tissues to adhere to a scaffold/matrix for tissue regeneration and drug delivery. Bioadhesive features can be engineered into/onto polymeric network/nanosystems by using small or large molecules that enable covalent or non-covalent molecular interactions with biological media (cells, tissues). Tissue-adhesive biomaterials or modifications to matrices can further improve performance of drug delivery systems and scaffolds by stabilizing their in-vivo location.",
      author: ["Vera BALAN", "Vlad URSACHI"],
      authorImg: "../../assets/blank.png",
    },
    {
      id: 8,
      title: "Bioinks and 3D Bioprinting",
      info: "Bioinks based on natural and sythetic polymers and 3D bioprinting of hydrogels.",
      author: ["Vera BALAN", "Vlad URSACHI"],
      authorImg: "../../assets/blank.png",
    },
  ],

  "Research Equipment": [
    {
      id: 1,
      title:
        "Cell culture microbiological safety hood with vertical laminar airflow and HEPA filters",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: "The AURA 2000 M.A.C. is a Microbiological Safety Cabinet 70% of fhe HEPA filtered air is therefore reciculated with thev remaining 30% being expelled through a dedicated exhaust HEPA filter. The cabinet is suitable for cell culture. The air flow control system provides a constant air flow unit the pressure across the HEPA filter emissing in reaches a level that the fan cannot compensate. The digital display and air velocity bargraph indicators give a continuous monitoring of the air flow conditions. Visible and audible alarms are actived when the laminar and exhaust air flow rates fall or exceed the fixed thresholds and when the front window is not closed securely. Sof touch keys on the control panel provide control of the lighiting,UV lamp,electrical power outlet and the solenoid valve which regulates the gas supply line. Electrical equipment accoding to EN 61010-1 International Standards and EMC directives. Noise level complies with EN 12469:2000, determined according to EN ISO 3744 and ISO 11201",
      producer: "Maria Butnaru",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 2,
      title: "Tekan plate reader with ELISA software",
      catalogName: "Tekan plate reader Sunrise",
      info: "Tekan plate reader Sunrise is a versatile microplate absorbance reader for 96-well plates providing all the functionality needed for the numerous applications in diagnostics, biotechnology and research laboratories. The device include Supports ELISA & kinetics, as well as agglutination reading. The Sunrise has an advanced temperature control option, consisting of a Peltier-based temperature control element for heating the plate from the bottom, distributing the airflow to each well via an array of metal tubes. • an additional top heating element located above the plate, to minimize evaporation and provide a good temperature distribution across the plate. Magellan software supports qualitative and quantitative data analysis for ELISAs and enzyme kinetics. It provides data exchange with Laboratory Information Systems (LIS) in ASCII & ASTM formats",
      producer: "Tekan",
      productionYear: "2014",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 3,
      title:
        "Organ bath Mayflower with System monitoring and stimulus generation D-79",
      catalogName:
        "The isolated Langendorff systems with Universal Perfusion System UNIPER UP-100",
      info: "The isolated Langendorff systems are designed to create the nearest physiological environment possible by incorporating solid state physiological perfusion circuit (S2P2C) technology for stable, temperature-controlled laminar flow. Our patented membrane afterload resistor allows for precise peripheral afterload adjustment in working heart perfusions without the need for high water columns that incur excessive stress on the aortic valve. Utilize a large heart chamber allowing for a variety of sensors (ECG, Monophasic Action Potential, Pacing, LVP, Temperature) to be precisely placed within the chamber. The system is apropriate for small species like mouse, rats and guinea pigs. Universal Perfusion System UNIPER UP-100 permit perfusion at constant pressure or constant flow without involving any modification of apparatus. Perfusion system permit hydrostatic pressure generation, low perfusate volume in use, perfusion pressure up to 300 mmHg possible. Equipped with oxygenator for optimal aeration of perfusate containing albumin or erythrocytes Mayflower Horizontal Tissue Bath System The Mayflower tissue bath is a horizontal tissue chamber with an integral contraction force measurement. It is completely open at the top and has a small bath volume of 3 - 5 ml. The compact and modular construction provides ideal conditions for investigations on small muscle preparations (urethra, papillary muscle, cavernous body), vascular rings, or tracheal rings.",
      producer: "Hugo Sachs Elektronik",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 4,
      title:
        "Dissolution tester, online system, 6 cells, the sampler and UV-VIS Spectrometer",
      catalogName: "UV-VIS ONLINE Dissolution System ERWEKA DT 700",
      info: "The unit is designed for dissolution tests and drug release studies with tablets, dragees, oblongs, capsules etc. and comprises of 8 test stations with glass, round-bottom beakers. The design of the unit eliminates most influences of different users to guarantee effective testing: autom. vessel centring, autom. height adjustment of stirrers etc. In addition the height adjustment of the stirrers, RPM, temperature, validation, calibration and service intervals may be constantly checked and the condition will be displayed by the integrated ”OQ Traffic Light”. The OQ menu helps the user to create the System Suitability Test for all parameters. The system include Peristaltic Pump with Verderprene tubing, UV-VIS (Shimadzu) and software ERWEKA Windows NT based Dissolution Software.",
      producer: "Erweka",
      productionYear: "2008",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 5,
      title: "Freeze dryer with adjustable temperature and vacuum",
      catalogName: " ",
      info: "controlled temperature and vacuum",
      producer: " ",
      productionYear: " ",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 6,
      title: "Incubator with humidified atmosphere and CO2",
      catalogName: " ",
      info: "temperature high precision ",
      producer: "Maria Butnaru",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 7,
      title: "Vertical electrophoresis",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: "Inverted microscope, filter phase contrast system",
      producer: "",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 8,
      title: "CUltrasonic homogenizer",
      catalogName: " ",
      info: "For cell disruption, emulsification and homogenising of materials, liquid degassing, dispersion, extraction and for sonochemistry.",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 9,
      title: "Automated Coagulation Analyzer",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 10,
      title: "Tools for polymer and composites-based scaffolds fabrication",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 11,
      title:
        "Inverted Laboratory Microscope with LED Illumination Leica DM IL LED",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: "With high-performance optics, ergonomic design, and precise 5W LED illumination, the Leica DM IL LED is ideal for cell and tissue culture, micromanipulation, and live cell examinations. The Leica DM IL LED features the most comprehensive array of contrast methods. High stability, plenty of space to work with tools, long working distances for large culture flasks, illumination without heat, and the separate electronics unit make work at the microscope easy and convenient. The fluorescence microscope adapts to each user with height-adjustable stages, Ergo tubes with variable height, and interpupillary distance and diopter settings.",
      producer: "Leica",
      productionYear: "2015",
      commisioningDate: "",
      equipmentPicture: "este poza ",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 12,
      title: "Inverted microscope with phase contrast system",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 13,
      title: "Incubator with orbital shaker for cell separation technics",
      catalogName: " ",
      info: " controlled temperature and shaking speed",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 14,
      title: "2 Centrifuges with refrigeration system",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 15,
      title:
        "Ultrasonic homogenizer, Sonopuls HD 2200, for synthesis of nanomaterials, emulsification and sonochemistry",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: "Ultrasonic homogenizers produce a high-power ultrasound with high amplitudes. The oscillations are transmitted and amplified down along the length of the horn and the probe into the aqueous sample to be treated. Applications:emulsificationof liquids difficult to mix, homogenizingof liquids, suspending, cell disruption(extraction of micro-organisms, tissue cells), degassingof liquis, accelerating of liquidsreactions, sonochemistry.Fields of application: disruption of cells, bacteria, virus, tissue, production of emulsions, homogenization of substances, sample preparation for HPLC, degassing of fluids, sample preparation for particle size analysis, acceleration of chemical reactions, waste-water analysis.",
      producer: "Bandelin",
      productionYear: "2014",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 16,
      title: "Steam autoclave with vacuum pump",
      catalogName: " ",
      info: "The avantages of this autoclave are: selection for solids and liquids, programmable auto-start (99 hours), connection to PC (USB) and control software. It is used for the sterilization of: culture media, glass, liquid, metallic objects, waste bags. The safety valve, the thermostat, the door blocking system (while positive pressure exists in the chamber) and the open door sensor make the autoclave saftey to use. It has a capacity of 21 L.",
      producer: "Raypa",
      productionYear: "2014",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 17,
      title: "Low freezer for biological materials",
      catalogName: " ",
      info: " ",
      producer: "",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 18,
      title: "Liquid nitrogen tank for cell storage",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 19,
      title: "Clean room for cell culture",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 20,
      title: "Multiparameter pH/temp/mV/CO2",
      catalogName: "",
      info: "Measures pH, temperature and mV in two ranges, in conjunction with ISE's and ORP electrodes. Clear dual display-temperature and pH or Mv. Simple calibration procedures - can be calibrated at one or two points aided by automatic buffer recognition. Automatic or manual temperature compensation. Simple to follow instructions on front panel of instrument.",
      producer: "Hanna Instruments",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 21,
      title: "Optical Microscopy (Olympus)",
      catalogName: "OLYMPUS ROUTINE MICROSCOPES CHK2",
      info: "The OLYMPUS ROUTINE MICROSCOPES CHK2 featureextraordinary operational versatility and the durable.To ensure superior viewing resolution with highcontrast, they are equipped with Olympus LB Seriesobjectives, which offer outstanding optical correctionright up to the periphery of the field of view. Featuring a built-in 20W halogen bulb, the CHK2 provides a binocular observation tube and mechanical stage to suit various microscopy requirements.",
      producer: "Olympus",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 22,
      title: "4 Drying ovens",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 23,
      title: "Water bath WB11",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 24,
      title: "4-Digits analytical balances",
      catalogName: " ",
      info: " ",
      producer: " ",
      productionYear: "",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 25,
      title: "Texture Analyzer TA XT plus",
      catalogName: " ",
      info: " ",
      producer: "Stable Micro Systems Ltd",
      productionYear: "2016",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "",
      DataSheet: "",
    },
    {
      id: 26,
      title:
        "Cell culture microbiological safety hood with vertical laminar airflow and HEPA filters",
      catalogName: "Bioair AURA 2000 M.A.C.",
      info: "Dimensiuni interne (W*D*H) – min 1150*600*660 mm Deschiderea de siguranta = min 200 mm Deschiderea maxima – min 420 mm Viteza de inflow – min 0.53±0.025 m/s Viteza de downflow – min 0.33±0.025 m/s Filtru HEPA - doua, 99.999% eficienta la 0.3um. Indicator durata viata lampa. Geam frontal motorizat. Sticlă securizată laminată din două straturi ≥ 5 mm. Anti UV. Lampa UV- 30W*1 UV timer, indicator durata viata UV, emisie la 253.7 nm. Lampa LEV - 14 W*2 Putere iluminare ≥1000 Lux Afișaj LCD: viteza flux de lucru, timp de lucru filtru și lampă UV, durata de viață a filtrului, umiditatea și temperatura, timpul de funcționare al sistemului. Sistem de control prin microprocesor. Sistem de aer - 70% aer recirculat, 30% aer evacuat. Alarma acustica si vizuala pentru: schimbare filtre, inaltime maxima deschidere geam frontal,viteza anormala a fluxului de aer. Material - Zona de lucru: otel inoxidabil 304L / Corpul principal: Oțel laminat la cald cu acoperire cu pulbere anti-bacteriană. Inaltime suprafata de lucru – min 750 mm. Accesorii: lampa LED, lampa UV*2, suport hota, telecomanda, intrerupator cu actionare la picior, valva de scurgere,prize rezistente la apa *2.",
      producer: " ",
      productionYear: "2019",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "10.001 € – 50.000 €",
      DataSheet: "",
    },
    {
      id: 27,
      title: "3D bioprinter",
      catalogName: "Cellink",
      info: " ",
      producer: " ",
      productionYear: "2020",
      commisioningDate: " ",
      equipmentPicture: "",
      PriceRange: "5.001 € - 10.000 €",
      DataSheet: "",
    },
    {
      id: 28,
      title: "3D Bioprinter",
      catalogName: "Cellink Inkredible +",
      info: " ",
      producer: " ",
      productionYear: "2021",
      commisioningDate: "",
      equipmentPicture: "",
      PriceRange: "10.001 € – 50.000 €",
      DataSheet: "",
    },
  ],
};

export default Data;
